Comandos usados para realizar el TP1


CREATE DATABASE TP1_Gatica;


use TP1_Gatica;


CREATE TABLE CUITS (CUIT_PAIS BIGINT PRIMARY KEY, PAIS VARCHAR(100), TIPO_SUJETO INT);


LOAD DATA INFILE '/var/lib/mysql-files/TABLACUITPAIS.csv' REPLACE INTO TABLE CUITS FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n' (CUIT_PAIS, PAIS, TIPO_SUJETO);


CREATE TABLE PERSONAS (PERSONA VARCHAR(10), SUJETO INT PRIMARY KEY);


INSERT INTO PERSONAS VALUES ('Juridica', 0);


INSERT INTO PERSONAS VALUES ('fisica', 1);


INSERT INTO PERSONAS VALUES ('otra', 2);


SELECT CUITS.CUIT_PAIS, CUITS.PAIS, PERSONAS.PERSONA FROM CUITS JOIN PERSONAS ON CUITS.TIPO_SUJETO = PERSONAS.SUJETO;


DESCRIBE CUITS;


DESCRIBE PERSONAS;


SELECT * FROM CUITS;