@startuml Clinica

(*) --> "solicitar Dni"

if "El paciente existe y esta cargado en la BBDD?" then 
    -->[True] "Solicitar fecha y hora de turno"
    --> "Turno asignado y almacenado en la BBDD"
    -right-> (*)
else 
    ->[False] "Solicitar datos"
    --> "Paciente almacenado en la BBDD"
    --> "Solicitar fecha y hora de turno"
@enduml